Cloud-Innovation-Partners/miniBRS

- dags/templates/main.py.jinja2
- plugins/mbrs/operators/servicenow_to_mysql_transfer_operator.py
- plugins/mbrs/utils/exceptions.py
- plugins/mbrs/utils/generator.py
- tests/dags/test_dag_validation_pytst.py
- Adds new file in plugins/mbrs/operators/ i.e servicenow_to_mysql_transfer_operator.py
- Modifies main.py.jinja2, adds the tempelate code for MYSQLOperator
- Modifies exception.py, adds MYSQLConnectionNotFoundException class
- Modifies is_sotrage_defined() method in generator.py, adds conditional statement for checking the mysql storage type
> Adds ServiceNow Operator - ServiceNowToMySQLOperator

- dags/templates/main.py.jinja2
- plugins/mbrs/operators/servicenow_to_postgres_transfer_operator.py
- plugins/mbrs/utils/exceptions.py
- plugins/mbrs/utils/generator.py
- Updates  main.jinja, adds template code for Postgresql operator
- Updates exception.py, adds Postgresql exception class
- Updates generator.py, adds storage conditional statement
- Adds ServiceNowToPostgresqlOperator class
> Fixes #7 : Adds servicenow_to_postgresql_operator

- plugins/mbrs/views/recovery_dashboard_view.py
> Removes dag cleanup from failed dags section

- plugins/mbrs/operators/servicenow_to_postgres_transfer_operator.py
Fixes typos in insert_data() method in servicenow_to_postgres_transfer_operator.py
> Updates servicenow_to_postgres_transfer_operator.py

- dags/__init__.py
- dags/dag_cleanup.py
- dags/dag_generator.py
- dags/generated/__init__.py
- dags/templates/__init__.py
- dags/templates/recovery_template.py.jinja2
- install
- plugins/mbrs/__init__.py
- plugins/mbrs/blueprints/__init__.py
- plugins/mbrs/blueprints/recovery_blueprint.py
- plugins/mbrs/hooks/servicenow_hook.py
- plugins/mbrs/menu_links/__init__.py
- plugins/mbrs/modals/__init__.py
- plugins/mbrs/modals/recovery_modals.py
- plugins/mbrs/operators/__init__.py
- plugins/mbrs/operators/common/email_operator.py
- plugins/mbrs/operators/common/servicenow_to_generic_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_dropbox_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_s3_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_sftp_transfer_operator.py
- plugins/mbrs/templates/recovery_dashboard.html
- plugins/mbrs/utils/__init__.py
- plugins/mbrs/utils/dates.py
- plugins/mbrs/utils/servicenow.py
- plugins/mbrs/utils/servicenow_client.py
- plugins/mbrs/utils/state.py
- plugins/mbrs/views/__init__.py
* removes authorship tag from code files
> Updates all project files

- dags/dag_generator.py
- plugins/mbrs/utils/generator.py
* Ignores postgres error due to duplicate value present in database
* Refactors code to PEP8 standards
> Updates dag_generator.py and generator.py

- plugins/mbrs/operators/common/servicenow_to_generic_transfer_operator.py
> Fixes issue #6 : removes spaces from the generated data files

- dags/dag_cleanup.py
Closes issue #4 
- adds docstring
- adds delete_airflow_log function
- adds dag documentation
> Fixes issue #4 : Update dag_cleanup to remove airflow historic logs

- plugins/mbrs/operators/servicenow_to_mysql_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_postgres_transfer_operator.py
- Modifies servicenow_to_postgres_transfer_operator.py and  servicenow_to_mysql_transfer_operator.py i.e replace the execute() method with executemany() method in both files
-Refactor code with pylint
> Modifies Postgresql and Mysql operators

- dags/dag_generator.py
- removes DAG instantiation from dag_generator file
> Fixes issue #14 : Hide dag_generator from UI

- dags/templates/main.py.jinja2
- plugins/mbrs/operators/servicenow_to_googledrive_transfer_operator.py
- plugins/mbrs/utils/exceptions.py
- plugins/mbrs/utils/generator.py
- Modifies main.jinja file i.e adds template code for Google Drive Operator
- Modifies generator.py i.e adds googledrive storage validation
- Modifies exception.py i.e adds GoogleDriveConnectionNotFoundException class
- Add servicenow_to_googledrive_transfer_operator.py file
> Fixes #9: Add servicenow_to_googledrive_transfer_operator

- install
- add create_google_drive_default_conneciton() method
- changes threshold from 10000 to 1000
> Update install script

- plugins/mbrs/operators/servicenow_to_mssql_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_mysql_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_postgres_transfer_operator.py
- Changes link_text to value_text in all database operators
> Modifies database operators

- plugins/mbrs/hooks/servicenow_hook.py
- plugins/mbrs/utils/servicenow_client.py
- add get schema function for table in hook and client
> Updates servicenow_hook and servicenow_client

- plugins/mbrs/operators/common/servicenow_to_generic_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_mysql_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_postgres_transfer_operator.py
- plugins/mbrs/utils/servicenow_client.py
Adds schema generation functionality in mysql and postgres operators
> Servicenow to database operators with incident problem sc tables

- plugins/mbrs/utils/exceptions.py
- plugins/mbrs/utils/generator.py
- Add InvalidTableException to exceptions module
- Add validation for special characters to create_dag method in generator module
> Update exceptions.py and generator.py

- dags/templates/recovery_template.py.jinja2
- plugins/mbrs/hooks/servicenow_hook.py
- plugins/mbrs/operators/common/servicenow_to_generic_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_mssql_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_mysql_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_postgres_transfer_operator.py
- plugins/mbrs/utils/exceptions.py
- plugins/mbrs/utils/generator.py
- plugins/mbrs/utils/servicenow_client.py
- Updates servicenow_to_mysql_transfer_operator and servicnow_to_postgres_operator with dynamic schema loading logic.
- Add `table_schema` method to servicenow_client
- Add `get_table_schema` method to the servicenow_hook
- Add validation check for special characters to the create_dag method of generator module
- Add InvalidTableName exception to the exception modules
> Merge v1-0-dev to v1-0-test

- plugins/mbrs/operators/servicenow_to_mssql_transfer_operator.py
- Adds schema generation functionality in servicenow_to_mssql_transfer_operator.py
> Updates servicenow_to_mssql_transfer_operator.py

- plugins/mbrs/operators/servicenow_to_mssql_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_mysql_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_postgres_transfer_operator.py
- Modifies all database operators to the dynamic column size during table creation
> Updates servicenow_to_mssql_transfer_operator.py, servicenow_to_mysql_transfer_operator.py and servicenow_to_postgres_transfer_operator.py

- plugins/mbrs/operators/servicenow_to_googledrive_transfer_operator.py
Add support for directory structure creation in concurrent execution
`mbrs/ServiceNow/incident/2020...`
> Updates ServiceNowToGoogleDriveTransferOperator

- plugins/mbrs/operators/servicenow_to_mssql_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_mysql_transfer_operator.py
- plugins/mbrs/operators/servicenow_to_postgres_transfer_operator.py
Add data type size constraint to the generated SQL query
> Update Database operator with the data type info
